[[redirects]]
  from = "/api/*"
  to = "https://zoomayor.io/api/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/img/*"
  to = "https://zoomayor.io/img/:splat"
  status = 200
  force = true