
[[redirects]]
  from = "/api/*"
  to = "http://147.45.244.129:3000/api/:splat"
  status = 200
  force = true
[[redirects]]
 from = "/img/*"
 to = "http://147.45.244.129:3000/img/:splat"
 status = 200
 force = true