[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Scheme = ["https"]}
[[redirects]]
  from = "/api/*"
  to = "https://147.45.244.129:3000/api/:splat"
  status = 200
  force = true
  headers = {
    Connection = "keep-alive",
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  }
[[redirects]]
  from = "/img/*"
  to = "https://147.45.244.129:3000/img/:splat"
  status = 200
  force = true
  headers = {
    Connection = "keep-alive",
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  }