[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/api/*"
  to = "https://zoomayor.io/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Cache-Control = "public, max-age=0, must-revalidate"}
[[redirects]]
  from = "/img/*"
  to = "https://zoomayor.io/img/:splat"
  status = 200
  force = true