
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/api/*"
  to = "https://api.zoomayor.io/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "https://zoomayor.io", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"}
[[redirects]]
  from = "/img/*"
  to = "https://api.zoomayor.io/img/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "https://zoomayor.io", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"}