[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/api/*"
  to = "https://147.45.244.129:3000/api/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/img/*"
  to = "https://147.45.244.129:3000/img/:splat"
  status = 200
  force = true