[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self https:; upgrade-insecure-requests;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Scheme = ["https"]}
[[redirects]]
  from = "/api/*" 
  to = "https://zoomayor.io/api/:splat"
  status = 200
  force = true
  headers = {
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Connection = "keep-alive"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  }
[[redirects]]
  from = "/img/*"
  to = "https://zoomayor.io/img/:splat" 
  status = 200
  force = true
  headers = {
    Cache-Control = "public, max-age=31536000"
    Connection = "keep-alive"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  }